apiVersion: kubeadm.k8s.io/v1beta3
kind: JoinConfiguration

discovery:
  bootstrapToken:
    token:   n8cb90.eihkre8s67kl684n   # เปลี่ยน
    apiServerEndpoint: "192.168.1.135:6443"  # IP Master
    caCertHashes:
      - "sha256:98bcbcac3880ff17c8a5aa042b43a87417e06e681dfa72093eb6be43783e8e9a"  # เปลี่ยน

nodeRegistration:
  name: worker-node-1 # name is optional, if not provided, the hostname will be used
  criSocket: "unix:///run/containerd/containerd.sock"
  kubeletExtraArgs:
    cgroup-driver: "systemd"