apiVersion: kubeadm.k8s.io/v1beta3
kind: JoinConfiguration

discovery:
  bootstrapToken:
    token:   w1awg6.xnw5dga09o9iehv3   # เปลี่ยน
    apiServerEndpoint: "192.168.1.129:6443"  # IP Master
    caCertHashes:
      - "sha256:601ecaaf14e38e5d03a63ea6d7a6072b03b4abd30962c6ea2af8d27ef3d0d702"  # เปลี่ยน

nodeRegistration:
  name: worker-node-1 # name is optional, if not provided, the hostname will be used
  criSocket: "unix:///run/containerd/containerd.sock"
  kubeletExtraArgs:
    cgroup-driver: "systemd"