apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
kbernetesVersion: v1.27.3
clusterName: kubeadm-cluster
networking:
  podSubnet: "192.168.0.0/16"

---
apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration

localAPIEndpoint:
  advertiseAddress: "192.168.1.129"
  bindPort: 6443

nodeRegistration:
  name: "control-plane"
  criSocket: "unix:///run/containerd/containerd.sock"
  kubeletExtraArgs:
    cgroup-driver: "systemd"
